<?php
ale_demo_media::add_image_to_media_gallery('ale_shop1',"http://alethemes.com/olins_base/media/blackwhite/shop1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop2',"http://alethemes.com/olins_base/media/blackwhite/shop2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop3',"http://alethemes.com/olins_base/media/blackwhite/shop3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop4',"http://alethemes.com/olins_base/media/blackwhite/shop4.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop5',"http://alethemes.com/olins_base/media/blackwhite/shop5.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop6',"http://alethemes.com/olins_base/media/blackwhite/shop6.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop7',"http://alethemes.com/olins_base/media/blackwhite/shop7.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop8',"http://alethemes.com/olins_base/media/blackwhite/shop8.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop9',"http://alethemes.com/olins_base/media/blackwhite/shop9.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop10',"http://alethemes.com/olins_base/media/blackwhite/shop10.jpg");