<?php
ale_demo_media::add_image_to_media_gallery('ale_img1',"http://alethemes.com/olins_base/media/blackwhite/1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img2',"http://alethemes.com/olins_base/media/blackwhite/2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img3',"http://alethemes.com/olins_base/media/blackwhite/3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img4',"http://alethemes.com/olins_base/media/blackwhite/4.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img5',"http://alethemes.com/olins_base/media/blackwhite/5.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img6',"http://alethemes.com/olins_base/media/blackwhite/6.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img7',"http://alethemes.com/olins_base/media/blackwhite/7.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img8',"http://alethemes.com/olins_base/media/blackwhite/8.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img9',"http://alethemes.com/olins_base/media/blackwhite/9.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img10',"http://alethemes.com/olins_base/media/blackwhite/10.jpg");