<?php
ale_demo_media::add_image_to_media_gallery('ale_img1',"http://alethemes.com/olins_base/media/jade/img1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img2',"http://alethemes.com/olins_base/media/jade/img2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img3',"http://alethemes.com/olins_base/media/jade/img3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img4',"http://alethemes.com/olins_base/media/jade/img4.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img5',"http://alethemes.com/olins_base/media/jade/img5.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img6',"http://alethemes.com/olins_base/media/jade/img6.jpg");
ale_demo_media::add_image_to_media_gallery('ale_p1',"http://alethemes.com/olins_base/media/jade/p1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_p2',"http://alethemes.com/olins_base/media/jade/p2.jpg");