<?php
ale_demo_media::add_image_to_media_gallery('ale_p1',"http://alethemes.com/olins_base/media/creative/p1.png");
ale_demo_media::add_image_to_media_gallery('ale_p2',"http://alethemes.com/olins_base/media/creative/p2.png");
ale_demo_media::add_image_to_media_gallery('ale_p3',"http://alethemes.com/olins_base/media/creative/p3.png");
ale_demo_media::add_image_to_media_gallery('ale_icon1',"http://alethemes.com/olins_base/media/creative/icon1.png");
ale_demo_media::add_image_to_media_gallery('ale_icon2',"http://alethemes.com/olins_base/media/creative/icon2.png");
ale_demo_media::add_image_to_media_gallery('ale_icon3',"http://alethemes.com/olins_base/media/creative/icon3.png");
ale_demo_media::add_image_to_media_gallery('ale_icon4',"http://alethemes.com/olins_base/media/creative/icon4.png");
ale_demo_media::add_image_to_media_gallery('ale_services_heading',"http://alethemes.com/olins_base/media/creative/services_header.jpg");
ale_demo_media::add_image_to_media_gallery('ale_service',"http://alethemes.com/olins_base/media/creative/service.jpg");