<?php
ale_demo_media::add_image_to_media_gallery('ale_shop1',"http://alethemes.com/olins_base/media/fashion/shop1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop2',"http://alethemes.com/olins_base/media/fashion/shop2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop3',"http://alethemes.com/olins_base/media/fashion/shop3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop4',"http://alethemes.com/olins_base/media/fashion/shop4.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop5',"http://alethemes.com/olins_base/media/fashion/shop5.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop6',"http://alethemes.com/olins_base/media/fashion/shop6.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop7',"http://alethemes.com/olins_base/media/fashion/shop7.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop8',"http://alethemes.com/olins_base/media/fashion/shop8.jpg");
ale_demo_media::add_image_to_media_gallery('ale_shop9',"http://alethemes.com/olins_base/media/fashion/shop9.jpg");