<?php
ale_demo_media::add_image_to_media_gallery('ale_work7',"http://alethemes.com/olins_base/media/travelphoto/work7.jpg");
ale_demo_media::add_image_to_media_gallery('ale_work8',"http://alethemes.com/olins_base/media/travelphoto/work8.jpg");
ale_demo_media::add_image_to_media_gallery('ale_work9',"http://alethemes.com/olins_base/media/travelphoto/work9.jpg");
ale_demo_media::add_image_to_media_gallery('ale_work10',"http://alethemes.com/olins_base/media/travelphoto/work10.jpg");
ale_demo_media::add_image_to_media_gallery('ale_work11',"http://alethemes.com/olins_base/media/travelphoto/work11.jpg");
ale_demo_media::add_image_to_media_gallery('ale_work12',"http://alethemes.com/olins_base/media/travelphoto/work12.jpg");
ale_demo_media::add_image_to_media_gallery('ale_work13',"http://alethemes.com/olins_base/media/travelphoto/work13.jpg");
ale_demo_media::add_image_to_media_gallery('ale_work14',"http://alethemes.com/olins_base/media/travelphoto/work14.jpg");